name: work-schedule-bot-biweekly

on:
  schedule:
    # Sundays at 14:05 UTC = 07:05 Phoenix
    - cron: "5 14 * * 0"
  workflow_dispatch: {}

permissions:
  contents: read

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - name: Biweekly gate
        id: gate
        run: |
          # Set this to the last Sunday you received a schedule
          ANCHOR_UTC="2025-08-31"
          TODAY_UTC="$(date -u +%Y-%m-%d)"
          secs_today=$(date -ud "$TODAY_UTC" +%s)
          secs_anchor=$(date -ud "$ANCHOR_UTC" +%s)
          days=$(( (secs_today - secs_anchor) / 86400 ))
          if [ $(( days % 14 )) -eq 0 ]; then
            echo "ok=true" >> $GITHUB_OUTPUT
            echo "Running. day_offset=$days"
          else
            echo "ok=true" >> $GITHUB_OUTPUT
            echo "Skipping. day_offset=$days"
          fi

      - uses: actions/checkout@v4
        if: steps.gate.outputs.ok == 'true'

      - uses: actions/setup-python@v5
        if: steps.gate.outputs.ok == 'true'
        with:
          python-version: "3.11"

      # Recreate OAuth files from Secrets
      - name: Write credentials.json
        if: steps.gate.outputs.ok == 'true'
        run: |
          cat > credentials.json <<'JSON'
          ${{ secrets.CREDENTIALS_JSON }}
          JSON

      - name: Write token.json
        if: steps.gate.outputs.ok == 'true'
        run: |
          cat > token.json <<'JSON'
          ${{ secrets.GMAIL_TOKEN_JSON }}
          JSON

      - name: Install dependencies
        if: steps.gate.outputs.ok == 'true'
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run bot
        if: steps.gate.outputs.ok == 'true'
        env:
          NOTION_TOKEN: ${{ secrets.NOTION_TOKEN }}
          NOTION_DATABASE_ID: ${{ secrets.NOTION_DATABASE_ID }}

          # Your DB schema
          NOTION_TITLE_PROP: Task
          NOTION_DATE_PROP: Date
          NOTION_TIME_PROP: Time
          NOTION_LOCATION_PROP: Location
          NOTION_NOTES_PROP: Notes
          NOTION_DAY_PROP: "Day of Week"

          # Gmail and parsing
          GMAIL_QUERY: ${{ secrets.GMAIL_QUERY }}
          TIMEZONE: America/Phoenix
          YOUR_NAME: Jeshad
          FILTER_BY_NAME: "true"
        run: python run.py

      - name: Upload debug artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: last-email
          path: |
            last_email.txt
            last_email.html
